### ISSUE TITLE
Trigger Multichannel support

### ISSUE THREAD

**Issue by robertaistleitner** [pusher/pusher_client_python#40]
Has anyone already tackled the problem with missing multichannel trigger support? It's already present in other pusher clients but I think due to the Python clients architecture this is more than a one-liner.. (as opposed to the others)

Your answers are appreciated,
Robert

**Comment by leggetter** [comment]
@robertaistleitner We're in progress of recommending https://github.com/pusher/pusher-http-python over this library.

It already support triggering the same event on multiple channels.

Do you have a hard requirement on using this library?

**Comment by robertaistleitner** [comment]
@leggetter Thanks for your very fast answer!

I've chosen this library because the other one is alpha and I need it for a production environment.. I'm kind of cautious when choosing alpha libraries.. ;)

I think I'll give it a try and read some code if it looks promising to me.

Thanks for your help!

**Comment by leggetter** [comment]
@robertaistleitner Understood.

We're actively doing some work on the other lib for an upcoming feature. So if you have any questions at all or see any problems please just post an issue to the repo.
